name: work-hub

services:
  redis:
    profiles: ["app"]
    image: 'redis:7-alpine'
    container_name: workhub-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    profiles: ["app"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workhub-app
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_MAIL_PASSWORD: ${SMTP_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - '8080:8080'
    depends_on:
      - redis
    restart: unless-stopped
    # CloudWatch Logs 설정
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: /ecs/workhub
        awslogs-stream: workhub-app
        awslogs-create-group: "true"
    # 로그 파일을 위한 볼륨 (백업용)
    volumes:
      - app_logs:/app/logs

  prometheus:
    profiles: ["monitor"]
    image: 'prom/prometheus:latest'
    container_name: workhub-prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped

  postgres-exporter:
    profiles: ["monitor"]
    image: 'prometheuscommunity/postgres-exporter:latest'
    container_name: workhub-postgres-exporter
    ports:
      - '9187:9187'
    environment:
      DATA_SOURCE_NAME: ${POSTGRES_EXPORTER_DATA_SOURCE_NAME}
    restart: unless-stopped

  grafana:
    profiles: ["monitor"]
    image: 'grafana/grafana:latest'
    container_name: workhub-grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://workhub.o-r.kr/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  redis_data:
  app_logs:
  prometheus_data:
  grafana_data:
