name: work-hub

services:
  redis:
    image: 'redis:7-alpine'
    container_name: workhub-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workhub-app
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_MAIL_PASSWORD: ${SMTP_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - '8080:8080'
    depends_on:
      - redis
    restart: unless-stopped
    # CloudWatch Logs 설정
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: /ecs/workhub
        awslogs-stream: workhub-app
        awslogs-create-group: "true"
    # 로그 파일을 위한 볼륨 (백업용)
    volumes:
      - app_logs:/app/logs

volumes:
  redis_data:
  app_logs: