spring:
  application:
    name: workhub

  profiles:
    active: dev
    include: secret  # 민감한 정보를 application-secret.yml에서 로드

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

file:
  upload:
    max-size: 52428800  # 50MB
