spring:
  application:
    name: workhub

  flyway:
    enabled: false
    baseline-on-migrate: false
    locations: classpath:db/migration
    baseline-version: 0

  profiles:
    active: dev
    include: secret  # 민감한 정보를 application-secret.yml에서 로드