spring:
  application:
    name: workhub

  profiles:
    active: dev
    include: secret  # 민감한 정보를 application-secret.yml에서 로드

  flyway:
    enabled: true  # Flyway bean 생성
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB