spring:
  application:
    name: workhub

  flyway:
    enabled: false
    baseline-on-migrate: false
    locations: classpath:db/migration
    baseline-version: 0

  profiles:
    # dev 프로필을 기본으로 사용하되 필요 시 SPRING_PROFILES_ACTIVE로 덮어쓴다
    default: dev
    group:
      dev:
        - secret
      prod:
        - secret
